/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.JFrame;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/**
 *
 * @author Brandon Collins
 */
public class BlackJack extends javax.swing.JFrame {

    int result;
    int bet;
  
    int myHandtotal = 0;
    int ace_spades_11 = 11;
    int ace_spades_1= 1;
    int two_spades = 2;
    int three_spades = 3;
    int four_spades = 4;
    int five_spades=5;
    int six_spades=6;
    int seven_spades=7;
    int eight_spades=8;
    int nine_spades=9;
    int ten_spades=10;
    int jack_spades=10;
    int queen_spades=10;
    int king_spades=10;
            //
    int ace_hearts_11 = 11;
    int ace_hearts_1= 1;
    int two_hearts= 2;
    int three_hearts = 3;
    int four_hearts = 4;
    int five_hearts=5;
    int six_hearts=6;
    int seven_hearts=7;
    int eight_hearts=8;
    int nine_hearts=9;
    int ten_hearts=10;
    int jack_hearts=10;
    int queen_hearts=10;
    int king_hearts=10;
            //
     int ace_diamonds_11 = 11;
    int ace_diamonds_1= 1;
    int two_diamonds= 2;
    int three_diamonds = 3;
    int four_diamonds = 4;
    int five_diamonds=5;
    int six_diamonds=6;
    int seven_diamonds=7;
    int eight_diamonds=8;
    int nine_diamonds=9;
    int ten_diamonds=10;
    int jack_diamonds=10;
    int queen_diamonds=10;
    int king_diamonds=10;
            //
    int ace_clubs_11 = 11;
    int ace_clubs_1= 1;
    int two_clubs= 2;
    int three_clubs = 3;
    int four_clubs = 4;
    int five_clubs=5;
    int six_clubs=6;
    int seven_clubs=7;
    int eight_clubs=8;
    int nine_clubs=9;
    int ten_clubs=10;
    int jack_clubs=10;
    int queen_clubs=10;
    int king_clubs=10; 

    
    int deck[] = new int[]{ace_spades_11, ace_spades_1,two_spades, three_spades, four_spades, five_spades, six_spades, seven_spades, eight_spades, nine_spades, ten_spades, jack_spades, queen_spades, king_spades,
        ace_hearts_11, ace_hearts_1,two_hearts, three_hearts, four_hearts, five_hearts, six_hearts, seven_hearts, eight_hearts, nine_hearts, ten_hearts, jack_hearts, queen_hearts, king_hearts,
        ace_diamonds_11, ace_diamonds_1,two_diamonds, three_diamonds, four_diamonds, five_diamonds, six_diamonds, seven_diamonds, eight_diamonds, nine_diamonds, ten_diamonds, jack_diamonds, queen_diamonds, king_diamonds,
        ace_clubs_11, ace_clubs_1,two_clubs, three_clubs, four_clubs, five_clubs, six_clubs, seven_clubs, eight_clubs, nine_clubs, ten_clubs, jack_clubs, queen_clubs, king_clubs
    
    };
    
    int card1 = new Random().nextInt(deck.length);
    int base_hand_1 = (deck[card1]);
    int card2 = new Random().nextInt(deck.length);
    int base_hand_2 = (deck[card2]);
    int myHand = base_hand_1 + base_hand_2;
    
    int dealerHand = base_hand_1 + base_hand_2;
    int win = 21;
    int lose = 0;
    InputStream music;
    
    public int check(){
    int myresHand = myHand;
    int dealresHand = dealerHand;

    if(myresHand == 21 ){
   JOptionPane.showMessageDialog(null, "YOU WIN!");
   int card1 = new Random().nextInt(deck.length);
    int base_hand_1 = (deck[card1]);
    int card2 = new Random().nextInt(deck.length);
    int base_hand_2 = (deck[card2]);
    int myHand = base_hand_1 + base_hand_2;
    
    int dealerHand = base_hand_1 + base_hand_2;
    }

   
     if(dealresHand == 21 ){
     JOptionPane.showMessageDialog(null, "I WIN!"); 
     int card1 = new Random().nextInt(deck.length);
    int base_hand_1 = (deck[card1]);
    int card2 = new Random().nextInt(deck.length);
    int base_hand_2 = (deck[card2]);
    int myHand = base_hand_1 + base_hand_2;
    
    int dealerHand = base_hand_1 + base_hand_2;
    }
        return 0;

    } 
    /**
     * Creates new form BlackJack
     */
    public BlackJack() {
        initComponents();
        JFrame BlackJackFrame = new JFrame();
        JOptionPane.showMessageDialog(null, "My name is Joel Swanson and I will be your dealer today!");
        firstCardLabel.setText("First Card value " + base_hand_1);
        secondCardLabel.setText("Second Card value " + base_hand_2);
        ResultLabel.setText("Result: " + myHand);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        BlackJackFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        dealerPanel = new javax.swing.JPanel();
        dealer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myCardsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        secondCardLabel = new javax.swing.JLabel();
        hitButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        doubleButton = new javax.swing.JButton();
        standButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        betLabel = new javax.swing.JLabel();
        betField = new javax.swing.JTextField();
        firstcard = new javax.swing.JPanel();
        firstCardLabel = new javax.swing.JLabel();
        ResultLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        javax.swing.GroupLayout BlackJackFrameLayout = new javax.swing.GroupLayout(BlackJackFrame.getContentPane());
        BlackJackFrame.getContentPane().setLayout(BlackJackFrameLayout);
        BlackJackFrameLayout.setHorizontalGroup(
            BlackJackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        BlackJackFrameLayout.setVerticalGroup(
            BlackJackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 0));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 900));

        dealer.setText("dealer");

        javax.swing.GroupLayout dealerPanelLayout = new javax.swing.GroupLayout(dealerPanel);
        dealerPanel.setLayout(dealerPanelLayout);
        dealerPanelLayout.setHorizontalGroup(
            dealerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dealerPanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(dealer)
                .addGap(64, 64, 64))
        );
        dealerPanelLayout.setVerticalGroup(
            dealerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealerPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(dealer)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/images/swanson.png"))); // NOI18N

        secondCardLabel.setText("Second Card Value");

        javax.swing.GroupLayout myCardsPanelLayout = new javax.swing.GroupLayout(myCardsPanel);
        myCardsPanel.setLayout(myCardsPanelLayout);
        myCardsPanelLayout.setHorizontalGroup(
            myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myCardsPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myCardsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myCardsPanelLayout.createSequentialGroup()
                        .addComponent(secondCardLabel)
                        .addGap(22, 22, 22))))
        );
        myCardsPanelLayout.setVerticalGroup(
            myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myCardsPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(secondCardLabel)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        hitButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        hitButton.setText("Hit");
        hitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitButtonActionPerformed(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menuButton.setText("Main Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        doubleButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        doubleButton.setText("Double Down");
        doubleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleButtonActionPerformed(evt);
            }
        });

        standButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        standButton.setText("Stand");
        standButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standButtonActionPerformed(evt);
            }
        });

        quitButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        betLabel.setText("Your Bet:");

        betField.setText("0.00");

        firstCardLabel.setText("First Card Value");

        javax.swing.GroupLayout firstcardLayout = new javax.swing.GroupLayout(firstcard);
        firstcard.setLayout(firstcardLayout);
        firstcardLayout.setHorizontalGroup(
            firstcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstcardLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(firstCardLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        firstcardLayout.setVerticalGroup(
            firstcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstcardLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(firstCardLabel)
                .addGap(69, 69, 69))
        );

        ResultLabel.setBackground(new java.awt.Color(255, 255, 255));
        ResultLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultLabel.setText("jLabel2");

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(786, 786, 786)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(dealerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitButton)
                            .addComponent(standButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doubleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(355, 355, 355)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(betLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67)
                .addComponent(myCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ResultLabel)
                .addGap(1077, 1077, 1077))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dealerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)))
                .addGap(13, 13, 13)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(doubleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hitButton)))
                .addGap(6, 6, 6)
                .addComponent(ResultLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(betLabel))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(300, 300, 300))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-450, 20, 2510, 970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "THANK YOU FOR PLAYING!");
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void standButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standButtonActionPerformed
        // TODO add your handling code here:

        int dealcard3 = new Random().nextInt(deck.length);
        int delhitHand = (deck[dealcard3]);

        dealerHand = dealerHand + delhitHand;
        dealer.setText("Result " + dealerHand);
        if(dealerHand == 17 || dealerHand  == 18 ||dealerHand  == 19 ||dealerHand  == 20){JOptionPane.showMessageDialog(null, "I'm Standing!");

            if(dealerHand > myHand || myHand > 21 || dealerHand == 21){

                JOptionPane.showMessageDialog(null, "I WIN!");
                int card1 = new Random().nextInt(deck.length);
                int base_hand_1 = (deck[card1]);
                int card2 = new Random().nextInt(deck.length);
                int base_hand_2 = (deck[card2]);
                int myHand = base_hand_1 + base_hand_2;

                int dealerHand = base_hand_1 + base_hand_2;

            }
            else{
                JOptionPane.showMessageDialog(null, "YOU WIN!");
                int card1 = new Random().nextInt(deck.length);
                int base_hand_1 = (deck[card1]);
                int card2 = new Random().nextInt(deck.length);
                int base_hand_2 = (deck[card2]);
                int myHand = base_hand_1 + base_hand_2;

                int dealerHand = base_hand_1 + base_hand_2;
            }

        }

        if(dealerHand > 21){
            JOptionPane.showMessageDialog(null, "I BUST!");
            int card1 = new Random().nextInt(deck.length);
            int base_hand_1 = (deck[card1]);
            int card2 = new Random().nextInt(deck.length);
            int base_hand_2 = (deck[card2]);
            int myHand = base_hand_1 + base_hand_2;

            int dealerHand = base_hand_1 + base_hand_2;}
    }//GEN-LAST:event_standButtonActionPerformed

    private void doubleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleButtonActionPerformed
        // TODO add your handling code here:

        bet *=2;
        int card3 = new Random().nextInt(deck.length);
        int double_down_hand = (deck[card3]);
        myHand = myHand + double_down_hand;
        ResultLabel.setText("Result " + myHand);
        if(myHand > 21){jLabel1.setText("BUST! ");
            JOptionPane.showMessageDialog(null, "YOU BUSTED!");
            int card1 = new Random().nextInt(deck.length);
            int base_hand_1 = (deck[card1]);
            int card2 = new Random().nextInt(deck.length);
            int base_hand_2 = (deck[card2]);
            int myHand = base_hand_1 + base_hand_2;

            int dealerHand = base_hand_1 + base_hand_2;

        }
        else if(myHand != 21){

            JOptionPane.showMessageDialog(null, "YOU LOST!");
            int card1 = new Random().nextInt(deck.length);
            int base_hand_1 = (deck[card1]);
            int card2 = new Random().nextInt(deck.length);
            int base_hand_2 = (deck[card2]);
            int myHand = base_hand_1 + base_hand_2;

            int dealerHand = base_hand_1 + base_hand_2;
        }
        else if(myHand == 21){

            JOptionPane.showMessageDialog(null, "YOU WON!");
            int card1 = new Random().nextInt(deck.length);
            int base_hand_1 = (deck[card1]);
            int card2 = new Random().nextInt(deck.length);
            int base_hand_2 = (deck[card2]);
            int myHand = base_hand_1 + base_hand_2;

            int dealerHand = base_hand_1 + base_hand_2;
        }
        else{
            jLabel1.setText("Result " + myHand);
        }
    }//GEN-LAST:event_doubleButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void hitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitButtonActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Result " + myHand);
        int card3 = new Random().nextInt(deck.length);
        int hitHand = (deck[card3]);

        myHand = myHand + hitHand;
        ResultLabel.setText("Result " + myHand);
        if(myHand == 21){
            JOptionPane.showMessageDialog(null, "YOU WIN!");
            int card1 = new Random().nextInt(deck.length);
            int base_hand_1 = (deck[card1]);
            int card2 = new Random().nextInt(deck.length);
            int base_hand_2 = (deck[card2]);
            int myHand = base_hand_1 + base_hand_2;

            int dealerHand = base_hand_1 + base_hand_2;
            
        }
        if(myHand > 21){
            JOptionPane.showMessageDialog(null, "YOU BUSTED!");
            int card1 = new Random().nextInt(deck.length);
            int base_hand_1 = (deck[card1]);
            int card2 = new Random().nextInt(deck.length);
            int base_hand_2 = (deck[card2]);
            int myHand = base_hand_1 + base_hand_2;

            int dealerHand = base_hand_1 + base_hand_2;
        }
    }//GEN-LAST:event_hitButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
         InputStream music;
        try{
           music = new FileInputStream(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\music\\shuffle.wav")); 
         AudioStream audios=new AudioStream(music);
         AudioPlayer.player.start(audios);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
            
        }
             card1 = new Random().nextInt(deck.length);
     base_hand_1 = (deck[card1]);
     card2 = new Random().nextInt(deck.length);
     base_hand_2 = (deck[card2]);
      firstCardLabel.setText("First Card value " + base_hand_1);
      secondCardLabel.setText("Second Card value " + base_hand_2);
      myHand = base_hand_1 + base_hand_2;
      dealerHand = base_hand_1 + base_hand_2;
              ResultLabel.setText("Result: " + myHand);
     
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame BlackJackFrame;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JTextField betField;
    private javax.swing.JLabel betLabel;
    private javax.swing.JLabel dealer;
    private javax.swing.JPanel dealerPanel;
    private javax.swing.JButton doubleButton;
    private javax.swing.JLabel firstCardLabel;
    private javax.swing.JPanel firstcard;
    private javax.swing.JButton hitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel myCardsPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel secondCardLabel;
    private javax.swing.JButton standButton;
    // End of variables declaration//GEN-END:variables
}
