/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/**
 *
 * @author Brandon Collins
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        JFrame MainMenu = new JFrame("mull");
    MainMenu.setSize(2000, 300);
    InputStream music;
              try{
           music = new FileInputStream(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\music\\Honky_Tonkin.wav")); 
         AudioStream audios=new AudioStream(music);
         AudioPlayer.player.start(audios);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        clickerField = new javax.swing.JLabel();
        TexasButton = new javax.swing.JToggleButton();
        SlotsButton = new javax.swing.JToggleButton();
        blackJackButton = new javax.swing.JToggleButton();
        RoulettesButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1500));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        clickerField.setBackground(new java.awt.Color(0, 0, 0));
        clickerField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clickerField.setForeground(new java.awt.Color(255, 255, 0));
        clickerField.setText("Please Click on the Game You want to Play!");
        getContentPane().add(clickerField);
        clickerField.setBounds(270, 400, 520, 50);

        TexasButton.setBackground(new java.awt.Color(204, 204, 255));
        TexasButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        TexasButton.setText("Texas Hold'em");
        TexasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TexasButton);
        TexasButton.setBounds(740, 480, 190, 50);

        SlotsButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        SlotsButton.setText("Slots");
        SlotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SlotsButton);
        SlotsButton.setBounds(380, 480, 130, 50);

        blackJackButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        blackJackButton.setText("BlackJack");
        blackJackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackJackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(blackJackButton);
        blackJackButton.setBounds(210, 480, 130, 50);

        RoulettesButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        RoulettesButton.setText("Roulettes");
        RoulettesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoulettesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RoulettesButton);
        RoulettesButton.setBounds(560, 480, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/images/menu.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 1500, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TexasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexasButtonActionPerformed
        // TODO add your handling code here:
        new Texas().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TexasButtonActionPerformed

    private void blackJackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackJackButtonActionPerformed
        // TODO add your handling code here:
        new BlackJack().setVisible(true);
              
        this.dispose();
    }//GEN-LAST:event_blackJackButtonActionPerformed

    private void RoulettesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoulettesButtonActionPerformed
        // TODO add your handling code here:
       new Roulettes().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_RoulettesButtonActionPerformed

    private void SlotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotsButtonActionPerformed
        // TODO add your handling code here:
        new Slots().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_SlotsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton RoulettesButton;
    private javax.swing.JToggleButton SlotsButton;
    private javax.swing.JToggleButton TexasButton;
    private javax.swing.JToggleButton blackJackButton;
    private javax.swing.JLabel clickerField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
