/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Brandon Collins
 */
public class Roulettes extends javax.swing.JFrame {
double ante = 5.00;
double bet;
    /**
     * Creates new form Roulettes
     */
    public Roulettes() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Welcome to the R.I.N.G. Roulette Table!");
    
    
 JOptionPane.showMessageDialog(null, "The Buy in is $5.00!");
 totalLabel.setText("Total: $"+ ante);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        betLabel = new javax.swing.JLabel();
        betField = new javax.swing.JTextField();
        spinButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        pickLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        wheel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        pickField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(51, 204, 0));

        betLabel.setBackground(new java.awt.Color(51, 153, 0));
        betLabel.setText("Enter Your Bet:");

        betField.setText("0.00");
        betField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betFieldActionPerformed(evt);
            }
        });

        spinButton.setBackground(new java.awt.Color(0, 204, 204));
        spinButton.setText("SPIN!");
        spinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButtonActionPerformed(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(255, 255, 51));
        menuButton.setText("MAIN MENU");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 0, 51));
        quitButton.setText("QUIT");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        pickLabel.setBackground(new java.awt.Color(51, 153, 0));
        pickLabel.setText("Your Pick");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wheel.setBackground(new java.awt.Color(102, 204, 0));
        wheel.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        wheel.setText("Spin the wheel!");
        jPanel1.add(wheel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        resultLabel.setBackground(new java.awt.Color(51, 153, 0));
        resultLabel.setText("Result:");

        pickField.setText("## Color");

        totalLabel.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(betLabel)
                            .addComponent(pickLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pickField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinButton)
                                        .addGap(68, 68, 68)
                                        .addComponent(menuButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 479, Short.MAX_VALUE)
                                .addComponent(quitButton)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickLabel)
                    .addComponent(pickField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betLabel)
                    .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinButton)
                    .addComponent(menuButton)
                    .addComponent(quitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void betFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betFieldActionPerformed

    private void spinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButtonActionPerformed
        // TODO add your handling code here:
        InputStream music;
        try{
           music = new FileInputStream(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\music\\roulet.wav")); 
         AudioStream audios=new AudioStream(music);
         AudioPlayer.player.start(audios);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
            
        }
        wheel.setText("");
        wheel.setIcon(new ImageIcon("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\rou.gif.gif"));
        
        String [] roul = new String[]{"0", "28", "9", "26", "30",
	"11", "7", "20", "32", "17", "5", "22", "34", "15", "3", "24", "36", "13", "1",
	"00", "27", "10", "25", "29", "12", "8", "19", "31", "18", "6", "21", "33", "16", 
	"4", "23", "35", "14", "2"};
        String color = "";
        int res1 = new Random().nextInt(roul.length);
        String resultOne = (roul[res1]);
        if(resultOne == "1" || 
		resultOne == "3" ||
		resultOne == "5" ||
		resultOne == "7" ||
		resultOne == "9" ||
		resultOne == "12" || 
		resultOne == "14" || 
		resultOne == "16" || 
		resultOne == "18" || 
		resultOne == "19" || 
		resultOne == "21" ||
		resultOne == "23" || 
		resultOne == "25" || 
		resultOne == "27" || 
		resultOne == "30" || 
		resultOne == "32" || 
		resultOne == "34" || 
		resultOne == "36" ){
		color = " Black";}
        else{
		color = " Red";}
        if(resultOne == "0" || resultOne =="00"){
		color = " Green";}
		String finalResult = resultOne ;
                String output = finalResult + color;
		System.out.print(output);
                resultLabel.setText("Result = " + output);
                String pick= pickField.getText();
                double res = ante-bet;
                double win = ante+bet;
                totalLabel.setText("Total: $"+ res);
                if(pick == output){
                 JOptionPane.showMessageDialog(null, "WINNER WINNER CHICKEN DINNER!"); 
                  totalLabel.setText("Total: $"+ win);
                }
                else{
                     try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException ex) {
            Logger.getLogger(Roulettes.class.getName()).log(Level.SEVERE, null, ex);
        }
                JOptionPane.showMessageDialog(null, "Try Again?"); 
                    
                }

    }//GEN-LAST:event_spinButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roulettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roulettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roulettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roulettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roulettes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betField;
    private javax.swing.JLabel betLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menuButton;
    private javax.swing.JTextField pickField;
    private javax.swing.JLabel pickLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton spinButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel wheel;
    // End of variables declaration//GEN-END:variables
}
