/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/**
 *
 * @author Brandon Collins
 */
public class Slots extends javax.swing.JFrame {

    String []img = {"Cherries-512.png", "Seven.png", "bar.jpg", "bell.jpg"};
    int bet;

   
                  
      
       

        
 
    /**
     * Creates new form Slots
     */
    public Slots() {
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        betField = new javax.swing.JTextField();
        betLabel = new javax.swing.JLabel();
        leverButton = new javax.swing.JButton();
        qutiButton = new javax.swing.JButton();
        slot1 = new javax.swing.JPanel();
        slot1Label = new javax.swing.JLabel();
        slot2 = new javax.swing.JPanel();
        slot2Label = new javax.swing.JLabel();
        slot3 = new javax.swing.JPanel();
        slot3Label = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        betField.setText(".00");
        betField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betFieldActionPerformed(evt);
            }
        });

        betLabel.setText("ENTER YOUR BET: ");

        leverButton.setText("PULL LEVER!");
        leverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leverButtonActionPerformed(evt);
            }
        });

        qutiButton.setText("QUIT");

        slot1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        slot1Label.setText("PULL THE LEVER!");

        javax.swing.GroupLayout slot1Layout = new javax.swing.GroupLayout(slot1);
        slot1.setLayout(slot1Layout);
        slot1Layout.setHorizontalGroup(
            slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slot1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(slot1Label)
                .addGap(25, 25, 25))
        );
        slot1Layout.setVerticalGroup(
            slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(slot1Label)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        slot2Label.setText("PULL THE LEVER!");

        javax.swing.GroupLayout slot2Layout = new javax.swing.GroupLayout(slot2);
        slot2.setLayout(slot2Layout);
        slot2Layout.setHorizontalGroup(
            slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slot2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(slot2Label)
                .addGap(26, 26, 26))
        );
        slot2Layout.setVerticalGroup(
            slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(slot2Label)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        slot3.setMaximumSize(new java.awt.Dimension(200, 200));
        slot3.setPreferredSize(new java.awt.Dimension(200, 200));
        slot3.setRequestFocusEnabled(false);

        slot3Label.setText("PULL THE LEVER!");

        javax.swing.GroupLayout slot3Layout = new javax.swing.GroupLayout(slot3);
        slot3.setLayout(slot3Layout);
        slot3Layout.setHorizontalGroup(
            slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(slot3Label)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        slot3Layout.setVerticalGroup(
            slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slot3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(slot3Label)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        menuButton.setText("Main Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leverButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(betLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menuButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 95, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)
                                .addComponent(qutiButton)
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betLabel)
                    .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leverButton)
                    .addComponent(qutiButton)
                    .addComponent(menuButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void betFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betFieldActionPerformed

    private void leverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leverButtonActionPerformed
        // TODO add your handling code here:
      BufferedImage image;
     BufferedImage image2;
     BufferedImage image3;
     BufferedImage image4;
     BufferedImage image5;
     BufferedImage image6;
           try {
            image = ImageIO.read(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\CHERRIES.png"));
             ImageIcon imageIcon = new ImageIcon(image);
             
             image2 = ImageIO.read(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\Seven.png"));
             ImageIcon imageIcon2 = new ImageIcon(image2);
             
             image3 = ImageIO.read(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\bar.jpg"));
             ImageIcon imageIcon3 = new ImageIcon(image3);
             
             image4 = ImageIO.read(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\Seven.png"));
             ImageIcon imageIcon4 = new ImageIcon(image4);
             
             image5 = ImageIO.read(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\Seven.png"));
             ImageIcon imageIcon5 = new ImageIcon(image5);
             
             image6= ImageIO.read(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\images\\Seven.png"));
             ImageIcon imageIcon6 = new ImageIcon(image6);
             
             
             
             
             
             ImageIcon[] arr = new ImageIcon[]{imageIcon, imageIcon2, imageIcon3, imageIcon4, imageIcon5, imageIcon6 };
            Random rnd = new Random();
            //ImageIcon index = new ImageIcon(rnd.n(arr.length));
            // handle exception...
            
                   String [] slot1 = new String[]{"7", "BAR", "BELLS", "CHERRIES", "BLUEBERRIES", "RING", "DICE"};
	  String [] slot2 =  new String[]{"7", "BAR", "BELLS", "CHERRIES", "BLUEBERRIES", "RING", "DICE"};
	  String [] slot3 =  new String[]{"7", "BAR", "BELLS", "CHERRIES", "BLUEBERRIES", "RING", "DICE"};
          
          
		int res1 = new Random().nextInt(slot1.length);
		String resultOne = (slot1[res1]);
		int res2 = new Random().nextInt(slot2.length);
		String resultTwo = (slot2[res2]);
		int res3 = new Random().nextInt(slot3.length);
		String resultThree = (slot1[res3]);
                
                if(resultOne == resultTwo && resultTwo ==resultThree){
                    JOptionPane.showMessageDialog(null, "JACKPOT!");
                    bet *=50;
                }
                 //slot1Label.setIcon(imageIcon2); 
                 slot1Label.setText("" + resultOne );
                // slot2Label.setIcon(imageIcon2); 
                 slot2Label.setText("" + resultTwo);
                 slot3Label.setText("" + resultThree);
        } catch (IOException ex) {
            Logger.getLogger(Slots.class.getName()).log(Level.SEVERE, null, ex);
        }
           
               InputStream music;
        try{
           music = new FileInputStream(new File("C:\\Users\\Brandon Collins\\Documents\\NetBeansProjects\\GUIS\\src\\guis\\music\\slot.wav")); 
         AudioStream audios=new AudioStream(music);
         AudioPlayer.player.start(audios);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
            
        }



                
                
    }//GEN-LAST:event_leverButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed
    private void qutiButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
       System.exit(0);
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField betField;
    private javax.swing.JLabel betLabel;
    private javax.swing.JButton leverButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton qutiButton;
    private javax.swing.JPanel slot1;
    private javax.swing.JLabel slot1Label;
    private javax.swing.JPanel slot2;
    private javax.swing.JLabel slot2Label;
    private javax.swing.JPanel slot3;
    private javax.swing.JLabel slot3Label;
    // End of variables declaration//GEN-END:variables
}
